### ISSUE TITLE
Unable to load existing OWL in Semantic Map Editor

### ISSUE THREAD

**Issue by albertK** [knowrob/knowrob#11]
When I tried to load and existing OWL file in Semantic Map Editor, the console output the following messages and just stuck there :

```
Feb 14, 2014 2:03:01 PM controlP5.ControlBroadcaster printMethodError
SEVERE: An error occured while forwarding a Controller event, please check your code at controlEvent
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at controlP5.ControlBroadcaster.invokeMethod(Unknown Source)
    at controlP5.ControlBroadcaster.broadcast(Unknown Source)
    at controlP5.Controller.broadcast(Unknown Source)
    at controlP5.Button.setValue(Unknown Source)
    at controlP5.Button.activate(Unknown Source)
    at controlP5.Button.mouseReleased(Unknown Source)
    at controlP5.Controller.setMousePressed(Unknown Source)
    at controlP5.ControllerGroup.setMousePressed(Unknown Source)
    at controlP5.ControlWindow.mouseReleasedEvent(Unknown Source)
    at controlP5.ControlWindow.mouseEvent(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at processing.core.PApplet$RegisteredMethods.handle(Unknown Source)
    at processing.core.PApplet.handleMouseEvent(Unknown Source)
    at processing.core.PApplet.dequeueMouseEvents(Unknown Source)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.core.PApplet.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:744)
Caused by: jpl.PrologException: PrologException: error(existence_error(procedure, /(rdf_has, 3)), context(:(system, /('<meta-call>', 1)), _27))
    at jpl.Query.get1(Query.java:336)
    at jpl.Query.hasMoreSolutions(Query.java:258)
    at jpl.Query.oneSolution(Query.java:688)
    at jpl.Query.hasSolution(Query.java:759)
    at edu.tum.cs.ias.knowrob.prolog.PrologInterface.executeQuery(PrologInterface.java:99)
    at edu.tum.cs.ias.knowrob.vis.applets.SemanticMapVisApplet.getItem(SemanticMapVisApplet.java:903)
    at edu.tum.cs.ias.knowrob.vis.applets.SemanticMapVisApplet.addObject(SemanticMapVisApplet.java:364)
    at edu.tum.cs.ias.knowrob.map.SemanticMapEditorForms.controlEvent(SemanticMapEditorForms.java:521)
    ... 22 more
```

What might be the cause and how to solve it? Thanks~

This is a same post as this:
http://answers.ros.org/question/132411/unable-to-load-existing-owl-in-semantic-map-editor/

**Comment by daniel86** [comment]
KnowRob does not include a semantic map editor anymore.
