### ISSUE TITLE
knowrob:vec3 seems to be invalid

### ISSUE THREAD

**Issue by JeremiasThun** [knowrob/knowrob#312]
When running the HermiT reasoner (in the implementation used in SOMA: https://github.com/ease-crc/soma/tree/master/.github/actions/hermit) on `knowrob.owl`, the class `vec3` is being rejected:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.semanticweb.HermiT.datatypes.UnsupportedDatatypeException: HermiT supports all and only the datatypes of the OWL 2 datatype map, see 
http://www.w3.org/TR/owl2-syntax/#Datatype_Maps. 
The datatype 'http://knowrob.org/kb/knowrob.owl#vec3' is not part of the OWL 2 datatype map and 
no custom datatype definition is given; 
therefore, HermiT cannot handle this datatype.
	at org.semanticweb.HermiT.datatypes.DatatypeRegistry.getDatatypeHandlerFor(DatatypeRegistry.java:79)
	at org.semanticweb.HermiT.datatypes.DatatypeRegistry.getDatatypeHandlerFor(DatatypeRegistry.java:85)
	at org.semanticweb.HermiT.datatypes.DatatypeRegistry.validateDatatypeRestriction(DatatypeRegistry.java:116)
	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.visit(OWLClausification.java:762)
	at org.semanticweb.owlapi.model.OWLDatatype.accept(OWLDatatype.java:141)
	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.convertDataRange(OWLClausification.java:748)
	at org.semanticweb.HermiT.structural.OWLClausification$NormalizedAxiomClausifier.visit(OWLClausification.java:575)
	at org.semanticweb.owlapi.model.OWLDataAllValuesFrom.accept(OWLDataAllValuesFrom.java:52)
	at org.semanticweb.HermiT.structural.OWLClausification.clausify(OWLClausification.java:161)
	at org.semanticweb.HermiT.structural.OWLClausification.preprocessAndClausify(OWLClausification.java:91)
	at org.semanticweb.HermiT.Reasoner.loadOntology(Reasoner.java:214)
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:205)
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:179)
	at org.semanticweb.HermiT.cli.CommandLine.main(CommandLine.java:381
```

Removing it seems to solve this issue.

https://github.com/knowrob/knowrob/blob/4d7af5484683cf2ff0aedd3b0126ae8c5077e035/owl/knowrob.owl#L81-L83

**Comment by kaviyachandran** [comment]
This issue is fixed in [PR](https://github.com/knowrob/knowrob/pull/318)
